# Generated by Django 2.0.13 on 2019-05-16 12:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190513_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-medium.png', upload_to=accounts.models.upload_profile),
        ),
    ]
