# Generated by Django 2.0.13 on 2019-10-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190825_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
