# Generated by Django 2.0.13 on 2020-04-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200424_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='descriprion',
            new_name='description',
        ),
    ]
