# Generated by Django 2.0.13 on 2020-04-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200426_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='ProjectImage',
        ),
    ]
