# Generated by Django 2.0.13 on 2020-05-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200426_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='inst_link',
            new_name='inst_username',
        ),
    ]
