# Generated by Django 2.0.13 on 2019-05-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='dislike',
            field=models.IntegerField(default=0, null=True, verbose_name='dislikes'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.IntegerField(default=0, null=True, verbose_name='likes'),
        ),
    ]
