# Generated by Django 2.0.13 on 2019-05-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='how_like',
            new_name='likes',
        ),
    ]
