# Generated by Django 2.0.13 on 2019-05-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190520_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='liked_by',
        ),
    ]
