# Generated by Django 2.0.13 on 2019-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190530_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
    ]
