# Generated by Django 2.0.13 on 2020-04-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200412_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
