# Generated by Django 2.0.13 on 2020-04-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_post_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
    ]
