version: '3'

services:
  web_service:
    build: .
    environment:
      - POSTGRES_USER='-'
      - POSTGRES_PASSWORD='-'
      - POSTGRES_DB='-'
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:10
    environment:
      - POSTGRES_USER='-'
      - POSTGRES_PASSWORD='-'
      - POSTGRES_DB='-'
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"